//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fast_food_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int MaCTHD { get; set; }
        public Nullable<int> MaHD { get; set; }
        public string MaMonAn { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual HD HD { get; set; }
        public virtual MONAN MONAN { get; set; }
    }
}
